leftnav:
- identifier: 844e6979-1fbe-44e9-ad9e-8f04228e1e02
  name: ER1
  pageRef: /external-resources/er1
  weight: 10
- identifier: 6d6c7f63-402d-4e02-b104-18f260a36143
  name: ER2
  pageRef: /pages/p1
  weight: 20
- identifier: 9e0d7ec8-91b9-4566-94b5-5f8c11c4765c
  name: ER3 OCW
  pageRef: /external-resources/er3
  weight: 30
- identifier: 9c40e22f-02a9-4de3-89ab-dc3de5382301
  name: ER4 live qa
  pageRef: /external-resources/er4-live-qa
  weight: 40
- identifier: 5a748079-dbad-4ed3-b028-85217c774a57
  name: ER5 MITOPEN
  pageRef: /external-resources/er-5-mitopen
  weight: 50
- identifier: 89c3f102-b2ba-4d1b-a121-19184f43f605
  name: ER6 ocw warning
  pageRef: /external-resources/er-6-ocw-with-warning
  weight: 60
- identifier: 6cfc52b6-4b49-4c8e-8a81-c33e6f6a5da4
  name: ER7 non OCW without warning
  pageRef: /external-resources/er7-non-ocw-without-warning
  weight: 70
