leftnav:
- identifier: 844e6979-1fbe-44e9-ad9e-8f04228e1e02
  name: ER1
  pageRef: /external-resources/er1
  weight: 10
- identifier: 6d6c7f63-402d-4e02-b104-18f260a36143
  name: ER2
  pageRef: /pages/p1
  weight: 20
- identifier: 9e0d7ec8-91b9-4566-94b5-5f8c11c4765c
  name: ER3 OCW
  pageRef: /external-resources/er3
  weight: 30
